server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_authuser
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: 'update'
      jdbc:
        lob.non-contextual-creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
viacep: 'viacep.com.br/ws'