server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_authuser
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      jdbc:
        lob.non-contextual-creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
