server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_course
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      jdbc:
        lob.non-contextual-creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true